# Generated by Django 4.2.23 on 2025-09-02 11:55

from django.db import migrations

# default_locale is supposed to be case-sensitive, although the collation
# we use in MySQL is hiding that. We erroneously set default_locale="es-es"
# on some collection in previous migration instead of es-ES, this fixes that.

def forwards_func(apps, schema_editor):
    Collection = apps.get_model('bandwagon', 'Collection')
    Collection.unfiltered.filter(default_locale='es-es').update(default_locale='es-ES')


def backwards_func(apps, schema_editor):
    Collection = apps.get_model('bandwagon', 'Collection')
    Collection.unfiltered.filter(default_locale='es-es').update(default_locale='es-es')


class Migration(migrations.Migration):

    dependencies = [
        ('bandwagon', '0009_update_default_locale_es_to_es-es'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
