# Generated by Django 4.2.23 on 2025-09-02 11:46

from django.db import migrations


# default_locale is supposed to be case-sensitive, although the collation
# we use in MySQL is hiding that. We erroneously set default_locale="es-es"
# on some add-ons in previous migration instead of es-ES, this fixes that.

def forwards_func(apps, schema_editor):
    Addon = apps.get_model('addons', 'Addon')
    Addon.unfiltered.filter(default_locale='es-es').update(default_locale='es-ES')


def backwards_func(apps, schema_editor):
    Addon = apps.get_model('addons', 'Addon')
    Addon.unfiltered.filter(default_locale='es-es').update(default_locale='es-es')


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0055_create_addon_listing_info_table'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
